export enum FinanceTransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum FinanceReferenceType {
  // Credits
  PARCEL_DELIVERED = 'PARCEL_DELIVERED',
  PARCEL_PARTIAL_DELIVERY = 'PARCEL_PARTIAL_DELIVERY',
  PARCEL_EXCHANGE = 'PARCEL_EXCHANGE',
  PARCEL_PAID_RETURN = 'PARCEL_PAID_RETURN',
  ADJUSTMENT_CREDIT = 'ADJUSTMENT_CREDIT',
  REFUND = 'REFUND',

  // Debits
  DELIVERY_CHARGE = 'DELIVERY_CHARGE',
  RETURN_CHARGE = 'RETURN_CHARGE',
  INVOICE_PAID = 'INVOICE_PAID',
  WITHDRAWAL = 'WITHDRAWAL',
  ADJUSTMENT_DEBIT = 'ADJUSTMENT_DEBIT',
  CLEARANCE = 'CLEARANCE',
}

