export enum StaffPosition {
  RIDER = 'RIDER',
  COURIER = 'COURIER',
  DISPATCHER = 'DISPATCHER',
  WAREHOUSE_ASSISTANT = 'WAREHOUSE_ASSISTANT',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  ADMIN_STAFF = 'ADMIN_STAFF',
  OTHER = 'OTHER',
}
